name: Traffic

on:
  schedule: 
    - cron: "15 23 * * 0"

jobs:
  update:
    name: Update

    runs-on: ubuntu-latest

    # env:
    #   TRAFFIC_PATH: meta/traffic.json

    steps:
      - uses: actions/checkout@v2

      - uses: nsaunders/traffic-lite@master
        with:
          repo: ${{ github.repository }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Commit update
        uses: EndBug/add-and-commit@v9
        with:
          # add: ${{ env.TRAFFIC_PATH }}
          add: meta/traffic.json
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: Log repository traffic.
